# Generated by Django 5.1.6 on 2025-04-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='accepted', max_length=100),
        ),
    ]
