# Generated by Django 5.1.6 on 2025-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0002_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive'), ('member', 'Member')], default='Member', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', max_length=100),
        ),
    ]
