# Generated by Django 5.1.6 on 2025-04-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0003_member_category_member_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='category',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='type',
        ),
    ]
