# Generated by Django 5.1.6 on 2025-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0004_delete_executive_rename_category_member_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='name',
            field=models.CharField(default='Test Scholarship', max_length=500),
            preserve_default=False,
        ),
    ]
