# Generated by Django 5.1.6 on 2025-04-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0005_scholarship_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='reciepient_email',
            new_name='recipient_email',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='reciepient_name',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='reciepient_phone',
            new_name='recipient_phone',
        ),
    ]
