# Generated by Django 5.1.6 on 2025-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0006_rename_reciepient_email_scholarship_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='recipient_id_number',
            field=models.CharField(default='GHA-65738837-6', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
