# Generated by Django 5.1.6 on 2025-05-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_admin', '0007_scholarship_recipient_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='date',
            new_name='created_at',
        ),
    ]
